---
- name: Set system hostname
  community.openwrt.uci:
    command: set
    key: system.@system[0].hostname
    value: "{{ flint2_hostname }}"
  notify: flint2 system changed

- name: Set LuCI time format
  community.openwrt.uci:
    command: set
    key: system.@system[0].clock_hourcycle
    value: "{{ flint2_clock_hourcycle }}"
  notify: flint2 system changed
