---
- name: Set system hostname
  when: flint2_hostname is defined
  community.openwrt.uci:
    command: set
    key: system.@system[0].hostname
    value: "{{ flint2_hostname }}"

- name: Set LuCI time format
  when: flint2_clock_hourcycle is defined
  community.openwrt.uci:
    command: set
    key: system.@system[0].clock_hourcycle
    value: "{{ flint2_clock_hourcycle }}"
