---
openwrt_gather_facts: true

ansible_user: root
ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"

openwrt_scp_if_ssh: smart
openwrt_remote_tmp: /tmp
openwrt_install_recommended_packages: true
openwrt_wait_for_connection: true
openwrt_wait_for_connection_timeout: 600
